<a href="https://colab.research.google.com/github/Abhilashg11/Data_science/blob/master/ANN(category).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,GridSearchCV
import keras
import tensorflow
from keras.layers import Dense,Dropout
from keras.datasets import mnist
from keras.models import Sequential
from keras.optimizers import RMSprop
from scikeras.wrappers import kerasClassifier

ModuleNotFoundError: ignored

In [2]:
df = pd.read_csv('/content/Churn.csv')

In [3]:
target = df['Exited']

In [4]:
target

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [9]:
features=df.drop(['RowNumber', 'CustomerId', 'Surname','Exited'],axis=1)

In [10]:
features.Geography.value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [12]:
lab_enc = LabelEncoder()

In [11]:
from sklearn.preprocessing import LabelEncoder

In [15]:
features['Geography']= lab_enc.fit_transform(features['Geography'])

In [16]:
features

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,Female,42,2,0.00,1,1,1,101348.88
1,608,2,Female,41,1,83807.86,1,0,1,112542.58
2,502,0,Female,42,8,159660.80,3,1,0,113931.57
3,699,0,Female,39,1,0.00,2,0,0,93826.63
4,850,2,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,Male,39,5,0.00,2,1,0,96270.64
9996,516,0,Male,35,10,57369.61,1,1,1,101699.77
9997,709,0,Female,36,7,0.00,1,0,1,42085.58
9998,772,1,Male,42,3,75075.31,2,1,0,92888.52
9999,792,0,Female,28,4,130142.79,1,1,0,38190.78

In [17]:
pd.get_dummies(features)

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male
0,619,0,42,2,0.00,1,1,1,101348.88,1,0
1,608,2,41,1,83807.86,1,0,1,112542.58,1,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0
3,699,0,39,1,0.00,2,0,0,93826.63,1,0
4,850,2,43,2,125510.82,1,1,1,79084.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,39,5,0.00,2,1,0,96270.64,0,1
9996,516,0,35,10,57369.61,1,1,1,101699.77,0,1
9997,709,0,36,7,0.00,1,0,1,42085.58,1,0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0,1
9999,792,0,28,4,130142.79,1,1,0,38190.78,1,0

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.75,random_state=100)

In [20]:
from sklearn.preprocessing import StandardScaler
std_sc = StandardScaler